// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureTraffic():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Networklist():Promise<any>;

export function StopCaptureTraffic():Promise<void>;
