// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureTraffic() {
  return window['go']['main']['App']['CaptureTraffic']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Networklist() {
  return window['go']['main']['App']['Networklist']();
}

export function StopCaptureTraffic() {
  return window['go']['main']['App']['StopCaptureTraffic']();
}
